version: "3.9"
services:
  frontend_xtracker:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - /etc/letsencrypt/live/jeaciaz.site:/ssl

  restapi_xtracker:
    build: ./backend
    entrypoint: /backend/docker-entry.sh
    ports:
      - "8080:8080"
    volumes:
      - ./backend/db:/db
