version: "3.9"
services:
  frontend_xtracker:
    build: ./frontend
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"

  restapi_xtracker:
    build: ./backend
    entrypoint: /backend/docker-entry.sh
    ports:
      - "8080:8080"
    volumes:
      - ./backend/db:/db
