"""add table for jwt blacklisting

Revision ID: 063659de2e76
Revises: d296ce5887ef
Create Date: 2023-08-27 12:49:28.575119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063659de2e76'
down_revision = 'd296ce5887ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jwt_blacklist',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('iat_until', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jwt_blacklist')
    # ### end Alembic commands ###
