"""create spendings table

Revision ID: 799ef2f6fb83
Revises: fb0a5855532d
Create Date: 2023-06-08 23:04:51.137051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '799ef2f6fb83'
down_revision = 'fb0a5855532d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spendings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('funnel_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['funnel_id'], ['funnels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spendings')
    # ### end Alembic commands ###
