"""change password to otp secret

Revision ID: d296ce5887ef
Revises: 49e891c30695
Create Date: 2023-08-21 19:57:26.212825

"""
from alembic import op
import sqlalchemy as sa
import pyotp


# revision identifiers, used by Alembic.
revision = 'd296ce5887ef'
down_revision = '49e891c30695'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM users")
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_secret', sa.String(), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM users")
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('otp_secret')

    # ### end Alembic commands ###
