class FunnelDoesNotExistException(ValueError):
    ...

class SpendingDoesNotExistException(ValueError):
    ...

class UserNotFoundException(ValueError):
    ...

class JwtTokenBlacklistedException(ValueError):
    ...